package lt.augus.mybatis.model;

import java.util.List;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    private Integer universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    private String registrationNo;
    private University university;
    private List<Course> courses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @return the value of PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @return the value of PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @param lastName the value for PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @return the value of PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public String getRegistrationNo() {
        return registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @param registrationNo the value for PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @mbg.generated Fri Mar 31 23:06:13 EEST 2017
     */
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }

    public University getUniversity() {
        return university;
    }

    public void setUniversity(University university) {
        this.university = university;
    }

    public List<Course> getCourses() {
        return courses;
    }

    public void setCourses(List<Course> courses) {
        this.courses = courses;
    }
}