package lt.augus.mybatis.dao;

import java.util.List;
import lt.augus.mybatis.model.StudentCourse;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Fri Mar 31 23:07:42 EEST 2017
     */
    int deleteByPrimaryKey(@Param("studentId") Integer studentId, @Param("courseId") Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Fri Mar 31 23:07:42 EEST 2017
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Fri Mar 31 23:07:42 EEST 2017
     */
    List<StudentCourse> selectAll();
}